### ISSUE TITLE
Train the Trainer Model for Product Manager 

### ISSUE THREAD

**Issue by abi-a** [hackforla/product-management#10]
### Overview
Because a good amount of volunteers are coming through the door very green, with little to no product experience.It would be important to set up a training model that will enhance their knowledge base that doesn't require the overhead time currently required to enable this. The suggestion would be for Bonnie and Abi to formalize a process that will support current product managers in becoming better educated on product management best practices and can support their counterparts in learning.

### Action Items
- [ ] Discuss this in a meeting for consensus 
- [ ] Set up a project leads meeting with product managers only to discuss thoughts 
- [ ] Document possible process and curriculum 
- [ ] Approach potential partners in the provision of courses/resources to facilitate this

**Comment by ExperimentsInHonesty** [comment]
Resolved by setting up a community of Practice for PMs and templates for all projects, etc.
