### ISSUE TITLE
Communication Strategy between Product Leads 

### ISSUE THREAD

**Issue by abi-a** [hackforla/product-management#12]
### Overview
A consistent touch base will need to be scheduled to ensure alignment on product plans and goals for each product. The expectation for these meetings is to understand the status, needs, and any leadership support that will be required. 

This will help solve a number of things to include :
1. The need for Bonnie being present at every meeting 

### Action Items
- [ ] Simple and easy reporting strategy for all project needs to be identified and socialized

**Comment by ExperimentsInHonesty** [comment]
Resolved by setting up a community of practice.
