### ISSUE TITLE
Create a NEW One Sheet: Food Oasis

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/product-management#127]
### Overview
Create the project one sheet so it can be shared with stakeholders and funders.

### Action Items
- [x] Make a copy of the one sheet template and store in the product management google drive/one sheet revisions
- [x] Review one sheet, fill in what details you can find and check off items on the checklist to see what it might be missing.
- [x] Setup a meeting with the PM to go over the project to get information to put onto the one sheet
- [x] Move this issue into the reviews column for leadership review

###
Checklist
- [ ] Include project logo (top right)
- [x] Overview
- [x] History and or last 6 months
- [x] Partners
- [x] Roadmap/next 6 months
- [x] Contact email (footer)
- [x] Github URL (footer)
- [x] Link to project page on hackforla.org (footer)
- [x] Slack channel (footer)
- [x] Last updated date (footer)
- [x] Hack for LA logo (bottom right) 

### Resources/Instructions
Check issue #3 for sample one sheets
[One Sheet Template](https://docs.google.com/document/d/1BCNkA3cEox1qp2803r1uDAtffEszQ2P34ZDHo4dKM0Y/edit?usp=sharing)
[Food Oasis One Sheet](https://docs.google.com/document/d/1ibYpIyshRo5VteE9vQYzjLDX4PKBURNYqdXITSkw6Hk/edit#heading=h.d4rcuyaxhqts)

**Comment by erigilg** [comment]
This is the first draft of the [one sheet](https://docs.google.com/document/d/1ibYpIyshRo5VteE9vQYzjLDX4PKBURNYqdXITSkw6Hk/edit#heading=h.d4rcuyaxhqts), some info is still missing and before submitting it to review could you @ktjnyc please check that the info is correct?

**Comment by ktjnyc** [comment]
@erigilg Erika, I reviewed and made some comments.

**Comment by erigilg** [comment]
@ktjnyc I finished updating the one sheet taking into account your comments. 

I'll submit it to review, the only thing pending is the right logo to use. I used the one that's used in food oasis site but @ExperimentsInHonesty mentioned something about a new one. Is this one the one? 
![image](https://user-images.githubusercontent.com/20444275/112527910-c4057180-8d60-11eb-829a-8057e4ac4a07.png)

If not could you help me with where I can find the most updated logo?

**Comment by ktjnyc** [comment]
Created an [issue on Food Oasis repo](https://github.com/hackforla/food-oasis/issues/917) to have the UI/UX team sort through the logos -

**Comment by ExperimentsInHonesty** [comment]
@ktjnyc any luck on this?
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ktjnyc** [comment]
@ExperimentsInHonesty the issue to confirm the logos is still open on our project board but i think the One Sheet is ready for review.

**Comment by ExperimentsInHonesty** [comment]
@ktjnyc I have changed the formatting on one sheet and a few words.  We will use this temporarily. When you get the logo sorted out, and find the stacked one, please add it to this issue and put it back in review and tag me and olivia.

**Comment by ktjnyc** [comment]
@ExperimentsInHonesty @Olivia-Chiong i've added the stacked logo to the doc.

**Comment by staceyrebekahscott** [comment]
Created new issue in Product-Mangement #348
