### ISSUE TITLE
Tracker: Templates & Guides

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/product-management#128]
### Overview
This is an issue to track the templates and guides we have available at Hack for LA

### Action Items

| Topic                                                                  | Guide Link                                                                                                | Template Link                                                                                                       | Issue                                                              | Status      | TG                | Comment |
| ---------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ | ----------- | ----------------- | ------- |
| One Sheet                                                              | [Guide](https://docs.google.com/document/d/14-nYNCjrMrC8lucUNBfLOFQZk2sWbkRlJgigWDAlqlI/edit?usp=sharing) | [Template](https://docs.google.com/document/d/1BCNkA3cEox1qp2803r1uDAtffEszQ2P34ZDHo4dKM0Y/edit?usp=sharing)        | [#74](https://github.com/hackforla/knowledgebase-content/issues/85)   | In Progress | Leadership review |         |
| Story Points                                                           | [Guide](https://docs.google.com/document/d/1GSFbnNWI7BsxIN3lPrRMN_qoILJ_ighc5ne-ED4MpKQ/edit)             | Template                                                                                                            | [#125](hackforla/knowledgebase-content#71) | In Progress | Gather examples   |         |
| Slack Reminders                                                        | [Guide](https://docs.google.com/document/d/1T-h3YJ8Pp4hsfq9ouRHRnwrrHROSz0-kQz5O9VTE62U/edit?usp=sharing) | N/A                                                                                                                 | [#88](https://github.com/hackforla/knowledgebase-content/issues/84)   | In Progress | Leadership review |         |
| Managing project's slack channel                                       | Guide                                                                                                     | N/A                                                                                                                 | [#50](https://github.com/hackforla/knowledgebase-content/issues/83)   | In Progress | Gather examples   |         |
| Adding resume bullets to your issue                                    | Guide                                                                                                     | Template                                                                                                            | [#120](hackforla/knowledgebase-content#101) | In Progress | Gather examples   |         |
| Competitive/comparative analysis                                       | Guide                                                                                                     | [Template](https://docs.google.com/spreadsheets/d/1ePxxsLpdC4MMvJICyMYljHawhs1j-hpFHZFOtB0fdDc/edit#gid=1259306930) | [#82](https://github.com/hackforla/knowledgebase-content/issues/19)   | In Progress | Create guide      |         |
| Landing page with mailing list                                         | Guide                                                                                                     | Template                                                                                                            | [#132](https://github.com/hackforla/knowledgebase-content/issues/17) | In Progress | Gather examples   |         |
| HfLA Google form design                                                | Guide                                                                                                     | Template                                                                                                            | [#23](https://github.com/hackforla/knowledgebase-content/issues/58)   | In Progress | Gather examples   |         |
| Figma effective practices                                              | Guide                                                                                                     | N/A                                                                                                                 | [#20](https://github.com/hackforla/knowledgebase-content/issues/25)   | In Progress | Create guide      |         |
| Responsible use of images (HfLA websites)                              | [Guide](https://docs.google.com/document/d/17AbUtj9aIA8G88O8AVJnyL1jz4cNQ3x740cmzO-2yzk/edit)             | N/A                                                                                                                 | [#707](https://github.com/hackforla/website/issues/707)            | In Progress | Create guide      |         |
| Product roadmap                                                        | Guide                                                                                                     | Template                                                                                                            | [#110](https://github.com/hackforla/knowledgebase-content/issues/59) | In Progress | Gather examples   |         |
| Eco-system mapping for topic area of project                           | Guide                                                                                                     | Template                                                                                                            | [#80](https://github.com/hackforla/knowledgebase-content/issues/73)   | In Progress | Gather examples   |         |
| Using Kanban for Project Management                                    | [Guide](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit)             | N/A                                                                                                                 | [#70](https://github.com/hackforla/knowledgebase-content/issues/16)   | In Progress | Guide review      |         |
| Creating a Miro account for your project                               | Guide                                                                                                     | N/A                                                                                                                 | [#33](https://github.com/hackforla/knowledgebase-content/issues/7)   | In Progress | Create guide      |         |
| Create/organize your project's Google drive                            | Guide                                                                                                     | N/A                                                                                                                 | [#49](https://github.com/hackforla/knowledgebase-content/issues/74)   | In Progress | Create guide      |         |
| PM interview                                                           | [Guide](https://docs.google.com/document/d/1GvEAtmFYpG1be2tcBADrlTCy4TTzNd0qGeit2voaOc4/edit?usp=sharing) | N/A                                                                                                                 | [#92](https://github.com/hackforla/knowledgebase-content/issues/13)   | In Progress | Create guide      |         |
| Project inventory items                                                | Guide                                                                                                     | Template                                                                                                            | [#72](https://github.com/hackforla/product-management/issues/72)   | In Progress | Draft template    |         |
| User stories                                                           | [Guide](https://docs.google.com/document/d/18Wmoe9n-GptmDe1FZWl_xmNqtH5dHk5z03nnp8_MATM/edit)             | [User story template](https://docs.google.com/document/d/1qAxo7KEAIOuKBaPzS2BYQM0XsyOgHdZ5ls-hS49iAcU/edit)         | [#21](https://github.com/hackforla/product-management/issues/21)   | In Progress | Guide review      |         |
| Personas                                                               | [Guide](https://docs.google.com/document/d/18Wmoe9n-GptmDe1FZWl_xmNqtH5dHk5z03nnp8_MATM/edit)             | Template                                                                                                            | [#21](https://github.com/hackforla/product-management/issues/21)   | In Progress | Guide review      |         |
| User journey                                                           | [Guide](https://docs.google.com/document/d/18Wmoe9n-GptmDe1FZWl_xmNqtH5dHk5z03nnp8_MATM/edit)             | Template                                                                                                            | [#21](https://github.com/hackforla/product-management/issues/21)   | In Progress | Guide review      |         |
| Communication Style for Document Creation                              | Guide                                                                                                     | N/A                                                                                                                 | [#22](https://github.com/hackforla/knowledgebase-content/issues/29)   | Ice box     | Gather examples   |         |
| How to use Figma on Open Source Teams                                  | Guide                                                                                                     | N/A                                                                                                                 | [#706](https://github.com/hackforla/website/issues/706)            | Ice box     | Gather examples   |         |
| Team roster                                                            | Guide                                                                                                     | [Template](https://docs.google.com/spreadsheets/d/1DdlWALlH_5HLr7IYFx_ptt3g36Sju-hb1dc34ak0y18/edit#gid=1806338047) |                                                                    | Completed   | Completed         |         |
| Terms and conditions for your project                                  | Guide                                                                                                     | Template                                                                                                            | [#114](https://github.com/hackforla/knowledgebase-content/issues/21) | Ice box     | Gather examples   |         |
| Product analysis best practices                                        | Guide                                                                                                     | N/A                                                                                                                 | [#73](https://github.com/hackforla/knowledgebase-content/issues/23)   | Ice box     | Gather examples   |         |
| Website style guide                                                    | [Guide](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)           | N/A                                                                                                                 | [#24](https://github.com/hackforla/knowledgebase-content/issues/75)   | Ice box     | Create guide      |         |
| How to start a new project at Hack for LA                              | Guide                                                                                                     | N/A                                                                                                                 | [#28](https://github.com/hackforla/product-management/issues/28)   | Ice box     | Gather examples   |         |
| Create a Wiki for your project                                         | [Guide](https://github.com/hackforla/product-management/issues/25#issuecomment-770112547)                 | [Template](https://github.com/hackforla/.github/wiki)                                                               | [#25](https://github.com/hackforla/product-management/issues/25)   | Ice box     | Create guide      |         |
| Data analysis tools                                                    | Guide                                                                                                     | N/A                                                                                                                 | [#152](https://github.com/hackforla/product-management/issues/152) | Ice box     | Gather examples   |         |
| Create a Readme for your project                                       | Guide                                                                                                     | Template                                                                                                            | [#153](https://github.com/hackforla/knowledgebase-content/issues/76) | Ice box     | Gather examples   |         |
| Hosting for your project                                               | Guide                                                                                                     | Template                                                                                                            | [#154](hackforla/knowledgebase-content#70) | Ice box     | Gather examples   |         |
| Prioritizing features                                                  | Guide                                                                                                     | Template                                                                                                            | [#155](https://github.com/hackforla/knowledgebase-content/issues/10) | Ice box     | Gather examples   |         |
| What does a PM do                                                      | Guide                                                                                                     | N/A                                                                                                                 | [#156](https://github.com/hackforla/product-management/issues/156) | Ice box     | Gather examples   |         |
| Strategy and vision                                                    | Guide                                                                                                     | Template                                                                                                            | [#157](https://github.com/hackforla/knowledgebase-content/issues/52) | Ice box     | Gather examples   |         |
| MoSCoW prioritization                                                  | Guide                                                                                                     | Template                                                                                                            | [#158](https://github.com/hackforla/knowledgebase-content/issues/51) | Ice box     | Gather examples   |         |
| Release Plan                                                           | Guide                                                                                                     | Template                                                                                                            | [#159](https://github.com/hackforla/knowledgebase-content/issues/8) | Ice box     | Gather examples   |         |
| Product requirements document                                          | [Guide](https://docs.google.com/document/d/1djX7_QFO7Aj9m2akud8Sctn_2A4jsinEYK3OHo32keE/edit#heading=h.qpz414wzo9l)                                                                                                      | Template                                                                                                            | [#160](https://github.com/hackforla/knowledgebase-content/issues/18) | Ice box     | Gather examples   |         |
| Theme epic feature story tasks                                         | Guide                                                                                                     | Template                                                                                                            | [#161](https://github.com/hackforla/knowledgebase-content/issues/50) | Ice box     | Gather examples   |         |
| Brand sprint                                                           | Guide                                                                                                     | Template                                                                                                            | [#162](https://github.com/hackforla/knowledgebase-content/issues/5) | Ice box     | Gather examples   |         |
| Product marketing objectives                                           | Guide                                                                                                     | Template                                                                                                            | [#163](https://github.com/hackforla/knowledgebase-content/issues/49) | Ice box     | Gather examples   |         |
| Mockups and wireframes                                                 | Guide                                                                                                     | Template                                                                                                            | [#164](https://github.com/hackforla/knowledgebase-content/issues/48) | Ice box     | Gather examples   |         |
| A/B testing                                                            | Guide                                                                                                     | Template                                                                                                            | [#165](https://github.com/hackforla/knowledgebase-content/issues/11) | Ice box     | Gather examples   |         |
| Meeting minutes                                                        | Guide                                                                                                     | Template                                                                                                            | [#166](https://github.com/hackforla/knowledgebase-content/issues/60) | Ice box     | Gather examples   |         |
| User research                                                          | Guide                                                                                                     | Template                                                                                                            | [#167](https://github.com/hackforla/knowledgebase-content/issues/45) | Ice box     | Gather examples   |         |
| Google fonts                                                           | Guide                                                                                                     | Template                                                                                                            | [#168](https://github.com/hackforla/knowledgebase-content/issues/44) | Ice box     | Gather examples   |         |
| Usability testing vs A/B testing                                       | Guide                                                                                                     | N/A                                                                                                                 | [#174](https://github.com/hackforla/knowledgebase-content/issues/43) | Ice box     | Gather examples   |         |
| Create and manage your Github repository                               | Guide                                                                                                     | Template                                                                                                            | [#175](https://github.com/hackforla/knowledgebase-content/issues/42) | Ice box     | Gather examples   |         |
| Github project board                                                   | Guide                                                                                                     | Template                                                                                                            | [#176](https://github.com/hackforla/knowledgebase-content/issues/41) | Ice box     | Gather examples   |         |
| Github issue templates                                                 | Guide                                                                                                     | Template                                                                                                            | [#177](https://github.com/hackforla/knowledgebase-content/issues/40) | Ice box     | Gather examples   |         |
| 1password                                                              | Guide                                                                                                     | N/A                                                                                                                 | [#178](https://github.com/hackforla/product-management/issues/178) | Ice box     | Gather examples   |         |
| Create an email for your project                                       | Guide                                                                                                     | N/A                                                                                                                 | [#179](https://github.com/hackforla/product-management/issues/179) | Ice box     | Gather examples   |         |
| Recruitment form                                                       | Guide                                                                                                     | Template                                                                                                            | [#180](https://github.com/hackforla/knowledgebase-content/issues/39) | Ice box     | Gather examples   |         |
| OKRs and WBS                                                           | Guide                                                                                                     | Template                                                                                                            | [#181](https://github.com/hackforla/knowledgebase-content/issues/38) | Ice box     | Gather examples   |         |
| Creating a Figma account for your project                              | Guide                                                                                                     | N/A                                                                                                                 | [#182](https://github.com/hackforla/knowledgebase-content/issues/37) | Ice box     | Gather examples   |         |
| Presentation deck for your project                                     | Guide                                                                                                     | Template                                                                                                            | [#183](https://github.com/hackforla/knowledgebase-content/issues/24) | Ice box     | Gather examples   |         |
| Website analytics software setup                                       | Guide                                                                                                     | N/A                                                                                                                 | [#184](https://github.com/hackforla/knowledgebase-content/issues/15) | Ice box     | Gather examples   |         |
| Create a Guide/Template for practical applications for Code of Conduct | Guide                                                                                                     | Template                                                                                                            | hackforla/knowledgebase-content#86                                                               | In Progress | Draft template    |         |
| How to assign and work on an issue                                     | [Guide](https://docs.google.com/document/d/15KE8jVvp2ZhmkX7MY7Rethoye0LF5H0Gb8F29lrqeG0/edit#)            | N/A                                                                                                                 | [#227](https://github.com/hackforla/knowledgebase-content/issues/87) | In Progress | Guide review      |         |
| Using 'details' and 'summary' tags in an issue                         | Guide                                                                                                     | N/A                                                                                                                 | [#228](https://github.com/hackforla/knowledgebase-content/issues/22) | In Progress | Gather examples   |         |
| Updating VRMS                                                          | Guide                                                                                                     | N/A                                                                                                                 | [#233](https://github.com/hackforla/knowledgebase-content/issues/36) | Ice box     | Gather examples   |         |
| Updating items on the project's website                                | Guide                                                                                                     | N/A                                                                                                                 | [#234](https://github.com/hackforla/knowledgebase-content/issues/35) | Ice box     | Gather examples   |         |
| How to make a pull request (for PMs)                                   | Guide                                                                                                     | N/A                                                                                                                 | [#235](hackforla/admin#43) | In Progress | Gather examples   |         |
| User interview                                                         | Guide                                                                                                     | Template                                                                                                            |                                                                    | In Progress | Gather examples   |         |  

### Resources/Instructions
[Spreadsheet Converter](https://tabletomarkdown.com/convert-spreadsheet-to-markdown/)
[Templates and Guides Google Sheet](https://docs.google.com/spreadsheets/d/1OJOKJDhUzzMzaFwmbGoOdh5Ohh53LCwS4u7LulVvBsQ/edit#gid=334170522)

**Comment by erigilg** [comment]
I updated the tracker for all the guides and templates I could find in the projects tab. I gave it some formatting as well, let me know if it is clear or if any guides/ templates are missing. 

[Templates and guides google sheet ](https://docs.google.com/spreadsheets/d/1OJOKJDhUzzMzaFwmbGoOdh5Ohh53LCwS4u7LulVvBsQ/edit#gid=334170522)

**Comment by sayalikotkar** [comment]
I created a new issue - #211

**Comment by ExperimentsInHonesty** [comment]
@Olivia-Chiong I have created this new issue, can you add it to the tracker?  https://github.com/hackforla/product-management/issues/228

**Comment by erigilg** [comment]
@ExperimentsInHonesty guide added to the tracker 👍

**Comment by ktjnyc** [comment]
Suggestions for additional guides:
How to update VRMS (and what it is) 
How to update items on the website (meeting times, etc)

**Comment by erigilg** [comment]
@ktjnyc added your suggestions to the tracker. 
@Olivia-Chiong what do you think should I create the issues for Katie's guides suggestions?

**Comment by Olivia-Chiong** [comment]
Yes, I think we should have one for project page on the website

And one for VRMS

**Comment by ktjnyc** [comment]
FYI, I saw this [today ](https://www.producthunt.com/posts/product-management-templates)- might be helpful for some of the guides we are creating.

**Comment by erigilg** [comment]
That is pretty cool Katie, that could help us for user personas, customer journeys and roadmaps. This could be useful so the templates don't have to be made from zero.

**Comment by ktjnyc** [comment]
Per issue - we should have a separate guide for how to make a pr - specifically how to do a pr using github's visual interface.

**Comment by erigilg** [comment]
@ktjnyc I would suggest you add the description in the issue #235 as well as the purpose so people that don't know what a pr is have a better idea?

**Comment by kcoronel** [comment]
Hii! The issue #222 is not included in the guide, let me know if there are any questions :)

**Comment by ExperimentsInHonesty** [comment]
We have closed this guide issue because its being handled by admin https://github.com/hackforla/product-management/issues/178#issuecomment-913004416

**Comment by fchan218** [comment]
Closing this issue as this has been replaced by Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the Product Repo:</summary>
<p>

<img width="354" alt="Screenshot 2024-10-26 at 11 42 24 AM" src="https://github.com/user-attachments/assets/6aa540a4-6075-49cd-87da-141a6fe17497">
</p>
</details>
