### ISSUE TITLE
 Guide Status Creation

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/product-management#202]
### Overview
We need to create a guide status so that we can keep track of the progress on each guide to maintain alignment. 

### Action Items
- [x] First, we need to create a spreadsheet to track all the guides and finalize a format for data collection
- [x] Next, we need to gather all of the guide information based on the selected format
- [ ] Then, a updated cadence needs to be finalized. 

### Resources/Instructions
[Guide Chart](https://docs.google.com/spreadsheets/d/1omYkR_WeploNuOkF3Pqsg6DhIdej5SS2EBbG9FRefbA/edit#gid=0)
[Guide Pages in Repository](https://github.com/hackforla/website/tree/gh-pages/_guide-pages)

**Comment by tarang100** [comment]
Bonnie says we need to create integrated tracking between the guides that are on the HfLA website and the guides that are on the Communities of Practice. Moving this issue here to speed that up.

**Comment by Olivia-Chiong** [comment]
@tarang100 we do have a template/guides tracking in the PM CoP. It's here #128

**Comment by Olivia-Chiong** [comment]
We have a guides tracker. Closing this issue.
