### ISSUE TITLE
PM CoP Meeting Agenda 2021

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/product-management#210]
### Overview
This issue tracks the agenda for the product management community of practice and weekly roll call for projects.

Please check in on the [Roll Call Spreadsheet](https://docs.google.com/spreadsheets/d/1hsV9S6AEDS7MeN9j4qR-koMk9wRXVqGiiAeCRkvowJI/edit?pli=1#gid=389106417) 

### Weekly Agenda
[Week of Feb 22 2021](https://github.com/hackforla/product-management/issues/135)
[Week of Mar 01 2021](https://github.com/hackforla/product-management/issues/138)
[Week of Mar 08 2021](https://github.com/hackforla/product-management/issues/171)
[Week of Mar 15 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-799929433)
[Week of Mar 22 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-805130868)
[Week of Mar 29 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-809637665)
[Week of Apr 05 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-814381039)
[Week of Apr 12 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-818312828)
[Week of Apr 19 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-823470871)
[Week of Apr 26 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-827898163)
[Week of May 03 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-832297457)
[Week of May 10 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-837205428)
[Week of May 17 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-843607769)
[Week of May 24 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-846475734)
[Week of May 31 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-852297188)
[Week of June 7 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-857223298)
[Week of June 14 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-861857398)
[Week of June 21 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-866340343)
[Week of June 28 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-870985542)
[Week of July 5 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-875992284)
[Week of July 12 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-879940870)
[Week of Aug 9 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-897206313)
[Week of Aug 16 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-901252931)
[Week of Aug 25 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-905806152)
[Week of Aug 30 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-907481934)
[Week of Sep 6 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-915670801)
[Week of Sep 13 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-920203345)
[Week of Sep 20 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-924981311)
[Week of Sep 27 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-928400827)
[Week of Oct 4 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-933941026)
[Week of Oct 11 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-941744655)
[Week Oct 18 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-946434316)
[Week of Oct 25 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-952522098)
[Week of Nov 3 2021](https://github.com/hackforla/product-management/issues/210#issuecomment-960247433)
[Week of Jan 5 2022](https://github.com/hackforla/product-management/issues/210#issuecomment-1005748322)

### Resources
[3-Month CoP Meeting Plan](https://docs.google.com/spreadsheets/d/1112Sx5ukwMY7GRsRorXO5lXPJb1iYpGP3iMcvN0BldA/edit#gid=0)

**Comment by Olivia-Chiong** [comment]
Agenda for Week of Mar 15 2021

- Discussion topic: Hack for LA PM pain points and brainstorming solutions for it.
- Please use #admin channel on Slack for any admin requests such as adding someone to repo, 1Password, etc
- Please read the Zoom Guide #172 and ensure best practices are used for your meetings
- Update topic tags for your repository to include `hack-for-la` and `civictechindex`
- If you have open roles on your team, please add them to the open roles board on each [Community of Practice](https://github.com/hackforla/communities-of-practice)
- Confirm you have access to the Product Management Community of Practice repo by checking issue #133 
- How HfLA uses Google drive - Do not request access when you cannot access a file in Google Drive. Ask the person to move it to the appropriate location in the project's Google Drive

**Comment by Olivia-Chiong** [comment]
Agenda for Week of Mar 22 2021

- Discussion topic: Developing Writing Skills as a Product Manager
- Call for volunteers to present future weekly topics (Great opportunity to practice presentation skills)
- Please use #admin channel on Slack for any admin requests such as adding someone to repo, 1Password, etc
- Please read the Zoom Guide #172 and ensure best practices are used for your meetings
- Update topic tags for your repository to include `hack-for-la` and `civictechindex`
- If you have open roles on your team, please add them to the open roles board on each [Community of Practice](https://github.com/hackforla/communities-of-practice)
- Confirm you have access to the Product Management Community of Practice repo by checking issue #133 
- How HfLA uses Google drive - Do not request access when you cannot access a file in Google Drive. Ask the person to move it to the appropriate location in the project's Google Drive

**Comment by ExperimentsInHonesty** [comment]
@Olivia-Chiong Can we add this to the next agenda?

Teaching everyone to do a comparative analysis by doing one of these
https://github.com/hackforla/community-survey-nc-websites/issues/15

**Comment by Olivia-Chiong** [comment]
Agenda for Week of Mar 29 2021

Discussion topic: Competitive & Comparative Analysis

We will have Randall (@Arjayellis), PM of BallotNav come to talk about how BallotNav created their analysis and how it was helpful in developing BallotNav's features. 

After that, we will have a short hands-on exercise on doing a comparative analysis for neighborhood council websites in LA County. This is a project that will have impact in the community and I believe it will be a good learning experience.

- Reminder about HfLA's [Code of Conduct](https://github.com/hackforla/codeofconduct)
- Call for volunteers to present future weekly topics (Great opportunity to practice presentation skills)
- Please use #admin channel on Slack for any admin requests such as adding someone to repo, 1Password, etc
- Please read the Zoom Guide #172 and ensure best practices are used for your meetings
- Update topic tags for your repository to include hack-for-la and civictechindex
- If you have open roles on your team, please add them to the open roles board on each Community of Practice
- Confirm you have access to the Product Management Community of Practice repo by checking issue #133
- How HfLA uses Google drive - Do not request access when you cannot access a file in Google Drive. Ask the person to move it to the appropriate location in the project's Google Drive

**Comment by Olivia-Chiong** [comment]
Agenda for Week of Apr 05 2021

Discussion topic: Agile methodologies

We will have Iffath (@DrIffathsultana), PM of Civic Tech Index, PMP® Certified Project Manager | Certified SAFe® 5 Product Owner come to talk about Agile and the different types of Agile methodologies.

- Reminder about HfLA's Code of Conduct
- Call for volunteers to present future weekly topics (Great opportunity to practice presentation skills)
- Please use #admin channel on Slack for any admin requests such as adding someone to repo, 1Password, etc
- Please read the Zoom Guide #172 and ensure best practices are used for your meetings
- Update topic tags for your repository to include hack-for-la and civictechindex
- If you have open roles on your team, please add them to the open roles board on each Community of Practice
- Confirm you have access to the Product Management Community of Practice repo by checking issue #133
- How HfLA uses Google drive - Do not request access when you cannot access a file in Google Drive. Ask the person to move it to the appropriate location in the project's Google Drive

**Comment by Olivia-Chiong** [comment]
Agenda for Week of Apr 12 2021

Discussion topic: Crafting a Great LinkedIn Profile

We will review LinkedIn profiles together and discuss what are some effective practices and strategies to making your profile standout.

- Reminder about HfLA's Code of Conduct
- Call for volunteers to present future weekly topics (Great opportunity to practice presentation skills)
- Please use #admin channel on Slack for any admin requests such as adding someone to repo, 1Password, etc
- Please read the Zoom Guide #172 and ensure best practices are used for your meetings
- Update topic tags for your repository to include hack-for-la and civictechindex
- If you have open roles on your team, please add them to the open roles board on each Community of Practice
- Confirm you have access to the Product Management Community of Practice repo by checking issue #133
- How HfLA uses Google drive - Do not request access when you cannot access a file in Google Drive. Ask the person to move it to the appropriate location in the project's Google Drive

**Comment by Olivia-Chiong** [comment]
Agenda for Week of Apr 19 2021

Discussion topic: Effective Communication Methods with UI/UX teams

This week we will have @daniellex0 Co-lead of the UI/UX Community of Practice come and discuss what are some of the best ways to provide constructive feedback for UI/UX folks and how to best collaborate with them.

**Comment by kcoronel** [comment]
@Olivia-Chiong not sure if this is the correct place for this, but my idea last week was to create an audit of PM tools out in the market and getting a count for folks within the community who can give a training on the tool. It can also be great to have a glossary of these tools and a quick summary of what it is good for.

**Comment by Olivia-Chiong** [comment]
Agenda for Week of Apr 27 2021

Discussion topic: Pre-launch user testing

This week we will be meeting with the 100 Automations team and testing out their pre-launch website. Come dogfood with us as we test drive the shiny new website and use your critical product lens on what works and what doesn't.

Other items on agenda
- All projects need to update their Hack for LA website project profile card as we are now including all current team members on the project profile page.

**Comment by Olivia-Chiong** [comment]
> @Olivia-Chiong not sure if this is the correct place for this, but my idea last week was to create an audit of PM tools out in the market and getting a count for folks within the community who can give a training on the tool. It can also be great to have a glossary of these tools and a quick summary of what it is good for.

Sounds good. Do you want to create an issue for this and start the ball rolling? I know some tools were already discussed in the list of topics issue.

**Comment by Olivia-Chiong** [comment]
Agenda for Week of May 03 2021

Discussion topic: What are your favorite product books and what are top 3 lessons you have learned from them?

Come share your favorite product books and help create a reading list for a future product book club for our CoP.

Other items on agenda

- Review of assigned items in the PM repository
- All projects need to update their Hack for LA website project profile card as we are now including all current team members on the project profile page.
- All Product Managers need to update their assigned issue on the PM CoP repository

**Comment by Olivia-Chiong** [comment]
Agenda for Week of May 17 2021

Discussion topic: Working & Networking meeting - We will be reviewing and assigning issues. Product Managers who are not yet assigned to a project will be provided shadow projects. After that, we will be doing a speed networking session in small groups.

**Comment by NivenPrasad** [comment]
Learning from Tuesday, May 18, 2021: great people with diverse backgrounds and multiple skills at HfLA. Loved meeting everyone 1:1!!!

**Comment by natenateo** [comment]
Fun fun

**Comment by connie-yu-dotcom** [comment]
Learning from Tuesday, May 18, 2021: We have great people at Hack for LA. Super supportive and we're all here to learn, grow, and not judge, it's an open safe space to become a Product Manager.

**Comment by Sihemgourou** [comment]
Really kindhearted people in the community, really glad to get to know them !

**Comment by Olivia-Chiong** [comment]
Agenda for Week of May 24 2021

Discussion topic: Soft skills - Importance of communication and how to lead with influence. The Civic Tech Index team recently encountered a situation where a team member was disappointed that their issue was reassigned and asked to be moved to a different team. The product managers @mariastudnicka @DrIffathsultana and @connie-yu-dotcom will share what led to the situation, how it was resolved and the lessons learned from it.

**Comment by Olivia-Chiong** [comment]
Agenda for Week of May 31 2021

Discussion topic: Project cards on the Hack for LA website

The UI/UX team will be coming to our CoP to get product feedback on the [project profile cards](https://www.hackforla.org/#projects) on the Hack for LA website. Put on your Product Goggles and come give your feedback on how we can improve the cards and what new features we could add to the roadmap to better promote our projects.

**Comment by Olivia-Chiong** [comment]
Agenda for week of June 7 2021

Discussion topic: Book club discussion. Inspired by Marty Cagan.

Other items for discussion:

- GitHub template for project updates:
Sample template - https://github.com/hackforla/product-management/issues/263 Linked from - https://github.com/hackforla/website/issues/new/choose
- Pathway to leadership for development team members - https://github.com/hackforla/website/issues/1623

**Comment by Olivia-Chiong** [comment]
Agenda for week of June 14 2021

Discussion topic: Project Progress, Open Roles, Guides/Issue Assignments

This week we are focusing on project updates, projects with open roles that need a product manager and issues/guides that are in progress.

If you are not currently assigned to a project, please make sure you join tonight to get an assignment.
If you have something pending review, this would also be a good meeting to come get some comments from other PMs. 
If your project has hit some blockers, bring it to the meeting and we will work on it together.

**Comment by Olivia-Chiong** [comment]
Agenda for week of June 21 2021

Discussion topic: Project Progress, Open Roles, Guides/Issue Assignments

Bonnie will be chairing the meeting. 

This week we are still focusing on project updates, projects with open roles that need a product manager and issues/guides that are in progress. 

If you are not currently assigned to a project, please make sure you join tonight to get an assignment.
If you have something pending review, this would also be a good meeting to come get some comments from other PMs.
If your project has hit some blockers, bring it to the meeting and we will work on it together.

**Comment by Olivia-Chiong** [comment]
Agenda for week of June 28 2021

Discussion topic: Open Roles, Guides/Issue & Project Assignments

This week we are still focusing on projects with open roles that need a product manager and issues/guides that are in progress.

If you are not currently assigned to a project, please make sure you join tonight to get an assignment.
If you have something pending review, this would also be a good meeting to come get some comments from other PMs.
If your project has hit some blockers, bring it to the meeting and we will work on it together.

**Comment by Olivia-Chiong** [comment]
Agenda for week of July 5 2021

Discussion topic: Google Drive Migration, Bonnie Training Sessions, Anonymous Team Member Conflict request

This week we are discussing the following
- Upcoming [Google Shared Drive](https://github.com/hackforla/product-management/issues/268) migration process
- Bonnie is going to be opening training sessions for product managers
- We have had an anonymous conflict submitted by a product manager that we will discuss

**Comment by Olivia-Chiong** [comment]
Agenda for week of July 12 2021

Discussion topic: QA testing - What, Who and How?

This week we have a special guest - [Matt Monday](https://www.linkedin.com/in/matthewmonday/) who will be sharing his experience as a PM at ESPN working closely with engineering and QA on numerous projects. After his sharing, we will have an open discussion on how we are approaching QA testing here at Hack for LA.

**Comment by Olivia-Chiong** [comment]
Agenda for week of August 9 2021

Discussion topic: Code of Conduct reporting template & Conflict management

This week @kcoronel will be sharing the wonderful guide and template she has created for Code of Conduct reporting. We will also dive into how to manage reporting of incidents.

**Comment by Olivia-Chiong** [comment]
Agenda for week of August 16 2021

Discussion topic: Product Management Resources

This week we take a look at Product Management resources, communities, websites, podcasts etc that help sharpen our skills, stay up to date on the latest trends, mentorship, collaboration with others, networking, and much more.

Come armed with your favorite resources to share and hear from others on what they read, watch and listen to!

**Comment by Olivia-Chiong** [comment]
Agenda for week of September 6th

Discussion topic: Kanban board management, labels and onboarding

This week Bonnie is going to go over labelling and proper use of Kanban on your projects, onboarding new PMs who need projects and troubleshooting any blockers.

**Comment by ebele-oputa** [comment]
Agenda for week of September 13th

Discussion topic: Bookclub discussion on Cracking the PM Interview by Gayle McDowell and Jackie Bavaro

Invited speaker: Jackie Bavaro

Other items for discussion:
- Volunteers to make a presentation during our CoP meeting on the 22nd and other dates

**Comment by ebele-oputa** [comment]
Agenda for Week of Sept 20 2021

Discussion topic: Different types of product management software and use cases
Opportunity for PMs to make impromptu presentations on the tools they use

- Call for volunteers to present future weekly topics (Great opportunity to practice presentation skills)
- Call for votes for next PM book reading - Issue #255 
- Introducing the PM/tech word of the week
- Experience profile updates

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty @Olivia-Chiong @ebele-oputa 
Suggestions for COP meetings:

- Seasoned volunteer PMs can do a presentation on how to go about checking items off of the Experience Profile.
- Any PM who has had a Linkedin profile workshop with Bonnie can do a presentation on how to fill in the Resume Content Builder.

They can do a short presentation and if there are more than one PMs who are familiar with these topics, they can hold sessions in breakout rooms?

**Comment by ebele-oputa** [comment]
Agenda for Week of Sept 27 2021

Discussion topic: Peer-to-peer Networking: What projects are we working on and what can be learned from our processes?

This week will have PM leads and their Co-leads talk to the CoP about their projects, the problems they have encountered and how they have solved the problems. The goal is for the community especially the new PMs to share ideas, ask questions and use the learnings in implementing their projects.

Note: EVERY project must be represented

Meeting structure:
- 3 mins project description: led by PM leads (1 person per project)
- Breakout rooms for Q & A: led by PM leads/co-leads. Timeslot: 20 mins
- General discussion

Other items:
- Vote next book for bookclub
- PM/tech word of the week

**Comment by ebele-oputa** [comment]
Agenda for Week of Oct 4 2021

Discussion topic: Experience profile and Mock interviews

This week we will practice how to give the best answer during a PM interview. We will take turns answering PM interview questions and giving feedback to other PMs on their answers. There will be break-out rooms for one-on-one interactions and a general discussion on what was learned.  Be prepared to tell us about yourself, your specific experience overcoming a challenge and your favourite product!

We will also have a brief session on the purpose of the experience profile for new PMs.

Other items:
- PM book for the month
- PM/tech word of the week

**Comment by priyatalwar** [comment]
Agenda for week of Nov 3rd, 2021

Discussion topic: Brainstorming more interview questions

This week we will be continuing with our interview series prep and will be discussing behavioral questions. Please don't come prepared since we want to see if you are able to think on your feet

- What was your most challenging project?
- Tell us about a project you enjoyed most or are passionate about.
- Tell us about a time when you created documentation for something.
- Tell us about a time when you owned a mistake 
- What was a project where you learned a lot?
- Tell us about a project you had to resolve an interpersonal conflict.
- Tell us about a time when you failed.
If you have any other questions, you'd like us to bring up please feel free to let us know and we will discuss.

Other items -
• Remind all present PMs to read the book for book club

**Comment by carolzjy** [comment]
Agenda for the week of Nov 10th, 2021

Discussion topic: Product Development Lifecycle

This week we will have an impromptu discussion on product development lifecycle. 

Other items -
• Remind all present PMs to read the book for book club

**Comment by priyatalwar** [comment]
Agenda for the week of Nov 17th, 2021

Discussion topic: Product Development Lifecycle

This week we will have a discussion on the product development lifecycle since we did not get to have it last week.

Other items -
• Remind all present PMs to read the book for book club

**Comment by priyatalwar** [comment]
Agenda for the week of Dec 1st, 2021

Discussion topic: Imposter Syndrome 

At some point in our life, we all deal with an imposter syndrome. Let's discuss what it is, your experiences and any tips to overcome it

Other items -
• Remind all present PMs to read the book for book club

• Nas to present the user research request on behalf of design systems

**Comment by Rabia2219** [comment]
Potential discussion topics:
- Tell us about your first week as a PM
- What additional skills do you think an aspiring PM can benefit from? SQL, Data Analytics, Jira (or any other project management software), etc

**Comment by priyatalwar** [comment]
More topics:
 - Data-driven PM - how to be more data-driven as a PM, both qualitatively and quantitatively, including choosing the right metrics (analytics), experimentation (such as A/B testing), and user research 
 -  Industry-specific PM speaker?
 - Communication: PM and UI/UX
 - Communication: How to communicate with Engineers
 - How to solve problems ambiguously as a PM
 - How to prioritize
 - How to influence without authority
 - How to create a pitch deck for a product to present to leadership 
 - How to do competitive analysis
 - How to do a comparative analysis
 - How to conduct requirements gathering
 
 I think I'm done now:)

**Comment by priyatalwar** [comment]
@carolzjy @ebele-oputa Update of Figjam workshop: Lissa has confirmed to conduct a FigJam workshop on Jan 5th (Wed) at 6 pm during our PM CoP

**Comment by ebele-oputa** [comment]
Agenda for Week of Jan 5 2022

Discussion topic: Guides Creation and welcome backs!!!!!

This week we will keep it simple silly (KISS principle) by doing a round of introductions. We will answer the questions
- What have you been up to since we last met?
- What are your goals for the new year?
- How can we help you stay accountable?
Next, we will conduct a workshop on guides creation. Guides are really important tools for ensuring standardisation within organizations and serve as a learning resource for individuals.

We will also have a brief session on the purpose of the experience profile for new PMs.

Other items:
Agenda topics for the month

**Comment by priyatalwar** [comment]
Happy New Year Everyone! Today we have a special guest, Lissa Aguilar who has graciously accepted to offer her time to conduct a FigJam workshop.

Agenda for Week of Jan 5 2022

Discussion topic: FigJam Workshop

This week Lissa Aguilar, UX Researcher at Pearson has offered to conduct a FigJam workshop at our Community of Practice.

- Round of introduction 
- Figjam workshop 
- Q&A
- Other agenda action items
 - New PMs:
- [ ]  confirm that you have access to google drive for Product Management CoP
- [ ] any questions about open PM roles and assignments of new PMs

**Comment by priyatalwar** [comment]
@layneam here is our agenda issue for the CoP

**Comment by layneam** [comment]
Thanks @priyatalwar ! As discussed earlier, here's a suggested blurb + agenda for PdM CoP I understand to be 20 April 2022.

> Hack for LA's product management Community of Practice meetings are starting again on 20 April, 2022. If you're new here, [Communities of Practice](https://github.com/hackforla/communities-of-practice) exist for each practice area (UI/UX, marketing, engineering, etc.). All volunteers are strongly encouraged to attend in order to give and receive mentorship, get to know your peers, and raise the standard of practice at Hack for LA.
> 
> On our next meeting agenda:
> 1. Introductions! Come tell other product managers across all active projects a few words about yourself and let us know what you're working on.
> 2. Peer instruction: Let's get in the rhythm of sharing knowledge and helping each other. A few projects still require a product manager onboarding/offboarding issue template to be created in their repositories ([see the full list here](https://github.com/hackforla/product-management/wiki/Onboard-Offboard)). We will break off into pairs and assist volunteers who need help to set these up. 
> 3. With any time remaining, feel free to stay for informal networking.
> 
> **Important pre-work**
> Anyone who plans to create their product manager onboarding/offboarding issue in the session, please ensure you find and bring the following information:
> - Name of your project's Slack channel(s)
> - Times/days of your relevant team meetings
> - Link to your team roster
> - Name of your project's 1password vault(s)
> - Your project's HfLA email address(es)
> - Your project's Google Drive link
> - Your project's GitHub team URL
> - Link to your project Figma

Because Priyanka is traveling, @ExperimentsInHonesty , tagging you in this comment as well.

**Comment by ExperimentsInHonesty** [comment]
I think the requirement to bring info will reduce the number of people who show up.  If we can make up some instruction on how to find those items, they could get support during to meeting if they are having trouble navigating or locating the relevant urls.
