### ISSUE TITLE
Project Inventory: VRMS

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/product-management#213]
### Overview
We need to make an inventory for this project so we understand what assistance this project needs and what examples of effective processes or practices this team might have.

### Action Items
- [ ] Check the project for the items on the check list below
- [ ] Mark off the items when you find it and include the links where available
- [ ] Provide comments on what you find in the issue and also highlight when they have a great example so we can use it for the organization

**Product**
- [x] [Readme](https://github.com/hackforla/VRMS/blob/development/README.md)
- [x] [Wiki](https://github.com/hackforla/VRMS/wiki)
- [x] [Google Drive](https://drive.google.com/drive/folders/1uxCkpcPtDjrhftBO-axU2g8hjXsxiLiS)
- [x] [GitHub Repository](https://github.com/hackforla/VRMS)
   - [x] [Project Board](https://github.com/hackforla/VRMS/projects/2)
   - [ ] [Issue Templates]() 
- [x] [Slack Channel](https://hackforla.slack.com/archives/CRGH5HM0Q)
- [x] 1Password
- [x] Project Email
   - [x] vrms@hackforla.org
   - [ ] projectname@gmail.com (You will need this for setting up some applications like MIro that use rate limiting. Do not send emails using this address) 
- [x] [Team Roster](https://docs.google.com/spreadsheets/d/1sMIPMDy7j6zDQ2-jF0xX2x-W-tEY8IcUiikmii7tVa0/edit#gid=0)
- [x] [Product One Sheet](https://docs.google.com/document/d/1lsRUAAMs1b60LOqQb9H6c4Ky9AbQ7QN4FB1XNErKxEs/edit)
- [ ] [Recruitment Form]()
- [x] [OKRs and WBS](https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit)
- [x] [Roadmap](https://docs.google.com/document/d/1BlhtbYBbSBlwSKNFupqUwdtKiUluCErIt0Mr4vNzxlA/edit)
- [ ] [Storypoints]()
- [ ] [Meeting Minutes Template]()

**Marketing**
   - [x] [Marketing Objectives](https://github.com/hackforla/marketing/issues/44)
      - [x] Create new issue using this template: [Define Marketing Objectives for VRMS project]
      - [x] Copy the link for the issue into the parentheses above
   - [x] [Collect Marketing Assets](https://github.com/hackforla/marketing/issues/45)
      - [x] Create new issue using this template: [Collect Marketing Assets for VRMS]
      - [x] Copy the link for the issue into the parentheses above
   
**UI/UX**
- [x] [Figma](https://www.figma.com/proto/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=26204%3A0&viewport=507%2C474%2C0.05351170524954796&scaling=min-zoom)
- [ ] [Miro]()
- [ ] [Presentation Deck]()
- [x] [Competitive Analysis](https://docs.google.com/spreadsheets/d/12hAejjAlz43DIdfvvT54hSgnAswWf1NLzBcc9VminBk/edit#gid=0)
- [x] [User Persona/Journeys](https://docs.google.com/presentation/d/1hDus73QA-HpYbIXyTg-Bhhe-LqunURZc2Ef0-LQIT6U/edit#slide=id.g76d58df4f9_0_292)
- [ ] [Communication Style Guide (including documents, spreadsheets and forms)]()
- [x] [User Research Guide/Template](https://docs.google.com/document/d/16TTC2vLN4IF20f-cRlUNOC-ar1nT1ileLXX9617bEEk/edit#heading=h.a2kcmwu5anfr)
- [ ] [Wireframes Template]()
- [ ] [Website analytics software setup]()

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by nagesh23nayak** [comment]
Had a meeting with @khushbooshah-PM 
**Date: 3/19/21 Time 3:00 PM PST**

Open Questions
Is Wireframe same as Figma?
What exactly is Presentation Deck? What is it related to? Is it related to any subject or context since Team has many Presentation decks
Ux Research > Included 'User Persona' Research document. Need confirmation
For OKR and WBS included MVP Requirement document. Need confirmation

**Comment by nagesh23nayak** [comment]
@Olivia-Chiong Need review

**Comment by Olivia-Chiong** [comment]
Reviewed in meeting on 3/23. Nagesh will continue to update the items.

**Comment by nagesh23nayak** [comment]
Updated 3/23

**Comment by Olivia-Chiong** [comment]
@nagesh23nayak the links for the issues you created on the marketing board should go into the main bullet point, not the sub bullet link.

**Comment by nagesh23nayak** [comment]
Moved the link to main bullet point.

**Comment by Olivia-Chiong** [comment]
Thanks for the good work @nagesh23nayak I am closing the issue.
