### ISSUE TITLE
Project Inventory: 311

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/product-management#214]
### Overview
We need to make an inventory for this project so we understand what assistance this project needs and what examples of effective processes or practices this team might have.

### Action Items
- [ ] Check the project for the items on the check list below
- [ ] Mark off the items when you find it and include the links where available
- [ ] Provide comments on what you find in the issue and also highlight when they have a great example so we can use it for the organization

**Product**
- [x] [Readme](https://github.com/hackforla/311-data/blob/dev/README.md)
- [x] [Wiki](https://github.com/hackforla/311-data/wiki)
- [x] [Google Drive](https://drive.google.com/drive/u/0/folders/10_KYe3pbZqiq6reeLA8zDDeIlz-4PxWM)
- [x] [GitHub Repository](https://github.com/hackforla/311-data)
   - [x] [Project Board](https://github.com/hackforla/311-data/projects/10)
   - [ ] [Issue Templates]() 
- [x] [Slack Channel](https://hackforla.slack.com/archives/CJY4R382X)
- [x] 1Password
- [ ] Project Email
   - [x] 311-data@hackforla.org
   - [ ] projectname@gmail.com (You will need this for setting up some applications like MIro that use rate limiting. Do not send emails using this address) 
- [x] [Team Roster](https://docs.google.com/spreadsheets/d/1c4pYPX8YgSzkZ4iE8fOG98py56n4umUmlq5FQ40yniI/edit#gid=0)
- [x] [Product One Sheet](https://docs.google.com/document/d/1WgTN4kTT2LNoNxq7AHp5tOl9RhMIBTjqYonPzEXPmkE/edit)
- [ ] [Recruitment Form]()
- [ ] [OKRs and WBS]()
- [x] [Roadmap](https://docs.google.com/spreadsheets/d/1TipvVwhifg9vFwaLBvJJRC6B2Kpjj1AULDGl5hWVV2o/edit#gid=0)
- [ ] [Storypoints]()
- [ ] [Meeting Minutes Template]()

**Marketing**
   - [ ] [Marketing Objectives]()
      - [ ] Create new issue using this template: [Define Marketing Objectives for [INSERT PROJECT NAME]](https://github.com/hackforla/marketing/issues/new?assignees=&labels=Level%3A+Learning%2C+Skill%3A+Brand+Strategy%2C+Skill%3A+Digital+Marketing%2C+Skill%3A+Media+Strategy%2C+documentation&template=define-marketing-objectives-for--insert-project-name-.md&title=Define+Marketing+Objectives+for+%5BINSERT+PROJECT+NAME%5D+project)
      - [ ] Copy the link for the issue into the parentheses above
   - [ ] [Collect Marketing Assets]()
      - [ ] Create new issue using this template: [Collect Marketing Assets for [INSERT PROJECT NAME]](https://github.com/hackforla/marketing/issues/new?assignees=&labels=feature%3A+marketing+inventory+checklist&template=collect-marketing-assets-for--insert-project-name-.md&title=Collect+Marketing+Assets+for+%5BINSERT+PROJECT+NAME%5D)
      - [ ] Copy the link for the issue into the parentheses above
   
**UI/UX**
- [x] [Figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1%3A5)
- [ ] [Miro]()
- [ ] [Presentation Deck]()
- [ ] [Competitive Analysis]()
- [x] [User Persona/Journeys](https://drive.google.com/drive/folders/1aDvI1pFHN5loFfIjS24tq9MRV-bajilm)
- [ ] [Communication Style Guide (including documents, spreadsheets and forms)]()
- [x] [User Research Guide/Template](https://drive.google.com/drive/folders/1W5uE5L07ZJGBqmrx1ycca-zLwNVHihFm)
- [ ] [Wireframes Template]()
- [ ] [Website analytics software setup]()

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by PLoiya** [comment]
@Olivia-Chiong Moving the issue to review section for review.

**Comment by Olivia-Chiong** [comment]
Thanks for the great work @PLoiya 

I am closing this issue.
