### ISSUE TITLE
Create a Guide: Website Style Guide and Design System

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/product-management#24]
### Overview
Product Managers, Designers and Developers need a style guide to make sure the website created is consistent.

### Action Items
- [ ] Review the existing examples project Style Guides and Design Systems
- [ ] Create your version in your project's figma
- [ ] add a link to your Communication Guide to list of Work in Progress versions below
- [ ] Review with ~Bonnie~ Design Systems team and revise as appropriate based on notes
- [ ] Finalize Guide and move link to finished resources

#### Work in Progress
[HackforLA.org Style Guide and Design System example](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
[100 Automations](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=243%3A363)

**Comment by ExperimentsInHonesty** [comment]
This issue has been replaced with the design systems team efforts and issue # https://github.com/hackforla/design-systems/issues/109

**Comment by fchan218** [comment]
<details><summary>Prior version of issue</summary>
<p>

### Overview
Product Managers, Designers and Developers need a style guide to make sure the website created is consistent.

### Action Items
- [ ] Review the existing examples project Style Guides and Design Systems
- [ ] Create your version in your project's figma
- [ ] add a link to your Communication Guide to list of Work in Progress versions below
- [ ] Review with ~Bonnie~ Design Systems team and revise as appropriate based on notes
- [ ] Finalize Guide and move link to finished resources

### Resources

#### Finished 

#### Work in Progress
[HackforLA.org Style Guide and Design System example](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
[100 Automations](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=243%3A363)
</p>
</details>

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the [INSERT COP NAME] Repo:</summary>
<p>

<img width="343" alt="Screenshot 2024-10-09 at 5 06 21 PM" src="https://github.com/user-attachments/assets/72c4b73a-a60f-4df0-acaa-9e74a0ffd6a4">
</p>
</details>
