### ISSUE TITLE
Product Management Book Club

### ISSUE THREAD

**Issue by NivenPrasad** [hackforla/product-management#255]
### Overview
We are starting a monthly book club at HfLA!

### Action Items
Come up with a list of PM books and pick books for each month.

### Resources/Instructions
**Books** 
- **Escaping the Build Trap by Melissa Perri** 
- Cracking the PM Interview by Gayle MacDowell and Jackie Bavaro
- Cracking the PM Career by Gayle MacDowell and Jackie Bavaro
- Inspired by Marty Cagan
- Empowered by Marty Cagan
- The Messy Middle by Scott Belsky
- Good strategy Bad Strategy
- Principles of Product Management by Peter Yang

Do we want to get the list then vote in the Slack after the Friday PM meeting?

Sidenote:
- Do we want to look at?: 
  - Blogs / Articles
  - [Resource repository](https://github.com/ProductHired/open-product-management) 
  - Podcasts e.g. Spotify: A Product Story, Agile Coaches Corner
 
 Discussion on what People Want to Learn:
 - Real experience pivoting from Business Analyst to PM
 - Product Manager mindset
 - Zoom in vs Zoom out

**Comment by erigilg** [comment]
The First 90 Days - Michael D Watkins

**Comment by natenateo** [comment]
How to Decide - Annie Duke, great for major decisions

**Comment by Olivia-Chiong** [comment]
The Design of Everyday Things - Don Norman

**Comment by ggrrettcchhenn** [comment]
Not sure that these are exactly product related books but here are some related books I'm interested in:
[A Civic Technologist's Practice Guide](https://www.goodreads.com/book/show/55225556-a-civic-technologist-s-practice-guide) by Cyd Harrell
[The Design of Everyday Things](https://www.goodreads.com/book/show/840.The_Design_of_Everyday_Things?ac=1&from_search=true&qid=3tOtaBg8LD&rank=1) by Donald A. Norman
[How to Win Friends and Influence People](https://www.goodreads.com/book/show/4865.How_to_Win_Friends_and_Influence_People?ac=1&from_search=true&qid=OXWuKUdBu8&rank=1) by Dale Carnegie
[Race After Technology](https://www.goodreads.com/book/show/42527493-race-after-technology?from_search=true&from_srp=true&qid=rOI4CSDaJD&rank=1) by Ruha Benjamin

**Comment by Olivia-Chiong** [comment]
Book for May is Inspired by Marty Cagan. The reading schedule is as follows

![image (3)](https://user-images.githubusercontent.com/75456721/117714180-6bacf680-b18b-11eb-9387-b8ba6b78f583.png)

**Comment by ebele-oputa** [comment]
I choose -
The Design of Everyday Things - Don Norman
Empowered by Marty Cagan (we would as well read the sequel)

**Comment by kcoronel** [comment]
I choose- 
Good strategy Bad Strategy
Cracking the PM Interview by Gayle MacDowell and Jackie Bavaro

**Comment by seenaiype** [comment]
Cracking the PM Interview by Gayle MacDowell and Jackie Bavaro
Good strategy Bad Strategy

**Comment by gigicobos** [comment]
The Messy Middle by Scott Belsky
Escaping the Build Trap by Melissa Perri

**Comment by sameergautam** [comment]
Escaping the Build Trap by Melissa Perri


-----------------------------------------
Can I suggest few more books to the repository??

1. [When coffee and kale compete](https://www.amazon.com/When-Coffee-Kale-Compete-products/dp/1534873066)
2. [Jobs to be Done - Theory to Practice ](https://www.amazon.com/Jobs-be-Done-Theory-Practice/dp/0990576744/)
3. [Hooked](https://www.nirandfar.com/hooked/)

**Comment by ag2463** [comment]
The Messy Middle by Scott Belsky

**Comment by DrSavings** [comment]
Cracking the PM Career by Gayle MacDowell and Jackie Bavaro

**Comment by Andan-Eddy** [comment]
The Messy Middle by Scott Belsky

**Comment by priyatalwar** [comment]
Decode and Conquer by Lewis Lin
The Lean Startup by Dan Olsen

**Comment by Olivia-Chiong** [comment]
Book for August is Cracking the PM Interview by Gayle McDowell and Jackie Bavaro

The reading schedule as follows:

![image](https://user-images.githubusercontent.com/75456721/128580678-8a473c86-7080-4333-8c97-340a90da9b2d.png)

**Comment by Hanastevenson** [comment]
The Making of Manager - Julie Zhuo.

**Comment by Hanastevenson** [comment]
I found a pretty good thread on twitter covering blogs, newsletters and book recommendations - https://twitter.com/jaysonrobinson/status/1423568645188472834

**Comment by kcoronel** [comment]
Thanks so much for being here! The frameworks in this book are super helpful, however I wonder if there is anything you would update to make the book more relevant for today?

**Comment by gigicobos** [comment]
How do you see the role of a Product Manager and the teams' structure transform in the next 5 years?

**Comment by kcoronel** [comment]
What are your top 3-tips for what aspiring PM's should include on their LinkedIn page ?

**Comment by kcoronel** [comment]
What time-management skills do you use on the daily?

**Comment by priyatalwar** [comment]
What advice do you have for someone who is just starting out on learning the art of saying "No".

**Comment by dddhoang** [comment]
1. The Messy Middle
2. Good strategy Bad Strategy
3. Escaping the Build Trap

**Comment by kevindphan** [comment]
1. Decode and Conquer
2. How to Win Friends and Influence People
3. Empowered

**Comment by Rabia2219** [comment]
Start with Why - Simon Sinek
Hooked - Nir Eyal
Strong Product People - Petra Willes

**Comment by thomasdemoner** [comment]
My top 3 votes for next book reading:

1. How to Win Friends and Influence People - Dale Carnegie
2. The Lean Startup - Dan Olsen
3. (New suggestion) Who Moved My Cheese - Spencer Johnson
      This last one is very short and easily done in a week (or even a day), but I really enjoy coming back to it.

**Comment by PLoiya** [comment]
1. Hooked
2. Empowered
3. Good strategy Bad Strategy

**Comment by priyatalwar** [comment]
1. Decode and Conquer
2. The Lean Start up
3. Empowered

**Comment by EchoProject** [comment]
1. Influence: The Psychology of Persuasion
2. The Basic Laws of Human Stupidity 
3. The Anatomy of Story: 22 Steps to Becoming a Master Storyteller

**Comment by citrusapple** [comment]
1. Cracking the PM career
2. Good strategy Bad Strategy
3. How to Win Friends and Influence People

**Comment by lrchang2** [comment]
1. The Messy Middle 
2. The Basic Laws of Human Stupidity
3. Good strategy Bad Strategy

**Comment by ebele-oputa** [comment]
Book for October is The Design of Everyday Things by Don Norman

The reading schedule as follows:

<img width="585" alt="Screenshot 2021-10-04 at 17 12 55" src="https://user-images.githubusercontent.com/67303685/135936698-4d3841ec-622c-4bd9-b75b-668283c1be4c.png">

**Comment by mxajPrice** [comment]
I am going to start a new issue/space for a book club.
