### ISSUE TITLE
Create Design System content for the HfLA website.

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/product-management#297]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image
     - [x]  Alt image text
  - [x] 1500 x 700 hero image (please do not put project title on hero image)
     - [x]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [x]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
  - [x]  What you are looking for skills wise
  - [x]  Partner(s)
  - [x]  Location
  - [x]  Status
- [ ]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by Hanastevenson** [comment]
@ExperimentsInHonesty @Olivia-Chiong Once we have this information how do we upload it to the website? Is the PM able to have access to the CMS test different artwork? Also is there a sign off process before uploading to the website?

**Comment by Olivia-Chiong** [comment]
@Hanastevenson there is no CMS, so there is no testing involved. Once this information is completed, it should be sent to the HFLA website team to be implemented

**Comment by Hanastevenson** [comment]
- [ ]  [600 x 400 image](https://drive.google.com/file/d/1X5FLl9PdU-lI-bWWY9H2Hpa5AAPZ_5Kz/view?usp=sharing)
- [ ]  Alt image text - 'Hack for LA logo and the title of the project, Design Systems'
- [ ]  [1500 x 700 hero image](https://drive.google.com/file/d/1MiwRrs3idDNf86CKoF7zILmWDD0vqm6y/view?usp=sharing) 
- [ ]  Alt image text 'Colourful illustrations of the elements that form a Design System'
- [ ]  Name of project
- [ ]  A blurb about your project
- [ ]  Links (github, slack channel url, Testing Site, Live Site, etc.)
- [ ]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
- [ ]  What you are looking for skills wise
- [ ]  Partner(s)
- [ ]  Location
- [ ]  Status

**Comment by abuna1985** [comment]
@Hanastevenson @ExperimentsInHonesty Per the issue instructions for [#2255](https://github.com/hackforla/website/issues/2255), I am attaching the comment below with screenshots of the proposed project card/profile for the Design Systems project. As soon as this is approved, I will complete a pull request to be added to the website.
https://github.com/hackforla/website/issues/2255#issuecomment-926411273

**Comment by Hanastevenson** [comment]
This has been completed.
