### ISSUE TITLE
CoP Guest Speaker- Arie Meir- Head of Product, Healthcare AI at Google- Friday, July 29, 2022

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/product-management#344]
### Overview
Arie Meir- Head of Product, Healthcare AI at Google. To speak during our CoP meeting on Friday, July 29, 2022.
- At Google for 8 years
- PhD from Berkeley

### Action Items
- Add questions in the comments below, to be sent to Arie in advance so he can cater his presentation to our questions. 

To confirm with Eric Cho via Slack:
- Can we record the presentation?
- Can we post it- For internal use? Or on YouTube Channel? 
- Can we use a photo to promote the presentation? 
- Are there any links to information about Arie that we can share?

Responses from Eric:

- Can we record the presentation?
  - No recording of any kind for any use.
- Can we post it- For internal use? Or on YouTube Channel?
  - No recording of any kind for any use.
- Can we use a photo to promote the presentation?
  - Could you expand on the promotion? Is there an example? Does photo refer to a photo of Arie? Where do promotions live? 
 Who owns the properties? (Responded that the promotion would be a posting on the PM Slack channel). 
- Are there any links to information about Arie that we can share?
  - He may share some documents with the group.
- About 1 week in advance should be plenty of to collect and review. Thanks!

**Comment by staceyrebekahscott** [comment]
Sent message to Eric via Slack to ask the questions listed above, and also asked how far in advance Arie needs the questions so he can prepare his presentation.

**Comment by EchoProject** [comment]
- What are common misconceptions about Google PMs and/or PMing at Google?  
- As a hiring manager, what signals are you looking for in a PM at different levels?

**Comment by staceyrebekahscott** [comment]
- [ ] Create calendar invite for this event. 

Request from Eric Cho: Also, can you add his email ([arie.coach@gmail.com](mailto:arie.coach@gmail.com)) and mine ([eric.cho@glassdoor.com](mailto:eric.cho@glassdoor.com)) to the calendar invite for this event?

**Comment by mxajPrice** [comment]
> 

@EchoProject when you say PM do you mean Product Manager or Project Manager?

**Comment by EchoProject** [comment]
@mxajPrice product

**Comment by ExperimentsInHonesty** [comment]
https://projectmanagementacademy.net/resources/blog/make-or-buy-analysis/

**Comment by yiminng** [comment]
1. What are some resources that you would recommend to support one's learning on AI/AI in Healthcare/ Product Management
2. I am currently in healthcare looking to transition into health tech, any advice on how to transition? 
3. What are some current issues or trends in the industry you notice? 
4. Are there any skills that are underrated as a PM?

**Comment by ychu196** [comment]
Questions:

- When developing pricing plans, how do you establish Individual plans and Team plans?
- When your product has a free version and a paid version, how do you assess whether a feature should be in the free or paid version?
- How do you go about establishing causation when A/B testing is not possible or if the n-size is too small?
- What are your thoughts on Causal Inference?

**Comment by Rabia2219** [comment]
- Everyone wants a unicorn PM, especially in tech. What are the 3 top skills that you think are relevant for a tech PM?
- There is a lot of debate on defining the roles for Program Managers, Project Managers and Product Managers. What has your experience at Google been like? Is there a clear cut defined role for each or do the responsibilities overlap?

**Comment by staceyrebekahscott** [comment]
Checklist from CoP Agenda for 07/22/22: [CoP Weekly Agenda 2022](https://github.com/hackforla/product-management/issues/131)

@yiminng Below is the checklist copied from the CoP meeting on 07/22/22:

- [ ] Any more questions to add? EOD today Deadline for additional questions.
- [ ]  Select questions to send in advance. 
- [ ]  Prepare posting for channel- see guest speaker posting in UI-UX Slack Channel
   - [ ]  Who will prepare posting? _Yi Min Ng_ 
- [ ]  Is there anyone who can finish up these final arrangements? _Yi Min Ng_
- [ ]  Send questions to Eric Cho. Eric will send questions to Arie. Questions should be sent to Eric no later than Monday, 07/25/22. 
- [ ]  Make sure posting is added to Product Slack Channel
   - [ ]  Bonnie will post an @channel once the post is created and added to the Product Slack Channels
- [ ]  Send Arie and Eric Zoom link for the meeting next week

I have started DM communication via Slack between myself, Yi Min and Eric to finish up preparations. Yi Min will take lead in completing the items above.

**Comment by staceyrebekahscott** [comment]
1.  As a Nonprofit, we experience a lot of team member turnover on our project teams. How would you advise going about creating a culture of inclusion that keeps team members connected to the mission under these conditions? 
2. What is your approach to setting goals for product and product teams? How can your framework be translated into the nonprofit sector, when effective nonprofits are measured by their impact on the greater good rather than revenue?

**Comment by staceyrebekahscott** [comment]
Guest speaker presentation and Q&A was a success. Closing this issue and removing assignees. 

@EchoProject @yiminng Thank you both for your contributions to getting this organized.
