### ISSUE TITLE
Update Project Profile: Food Oasis

### ISSUE THREAD

**Issue by tarang100** [hackforla/product-management#35]
### Overview
As a product manager, I need to make sure that all the projects that are listed on the HfLA website are up to date so that my customers(visitors) can get an accurate picture of each of the projects.

### Project card
https://www.hackforla.org/projects/food-oasis

### Action Items
Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
- [x] title
- [ ] description
- [x] image
- [ ] leadership
  - [ ] Member Name
  - [ ] Role
  - [ ] Slack Member ID
  - [ ] Github Handle
- [x] links
  - [ ] Github
  - [ ] Slack
  - [ ] Test Site
  - [ ] Demo Site
  - [ ] Site
- [x] looking
- [ ] technologies
- [ ] location
- [ ] partner
- [ ] tools
- [ ] status

**Comment by tarang100** [comment]
Reached out to Jenny Mikesell via Slack on 11th January 2021 at 5:51 am PST / 7:21 pm IST

Tarang Gupta  7:21 PM

> Hi Jenny,
> Hope you don't mind me pinging you directly. I am a Product Manager with HfLA Website team and need your inputs on the following issue
> https://github.com/hackforla/website/issues/876
> Would you be kind enough to go through the issue once and mention any updates required as comments? Do let me know if you have any questions. Thanks!

**Comment by ExperimentsInHonesty** [comment]
Meeting Times
Tuesday 6:30pm, Duration 1 hour, PM meeting
Thursday 6:00pm, Duration 1 hour, Developer Meeting

**Comment by ahdithebomb** [comment]
@pawan92  please let us know if you can attend their meetings this Thursday and next Tuesday to get updates.

**Comment by ahdithebomb** [comment]
Sent @pawan92  a message on slack.

**Comment by ExperimentsInHonesty** [comment]
@pawan92 was supposed to go to the thursday meeting.  But I don't see any update here.  He is also supposed to go to the Tuesday meeting.  @pawan92 please update what if anything you found out at the Thursday meeting.

**Comment by pawan92** [comment]
Update: I pinged fola slack channel multiple times on meeting time and meeting link for last night but did not get a reply. Tried @ the whole channel but that seems to bee disabled. I have also pinged @jpmikesell but have not gotten a response. I will bother them some more and also look into who else is on the project so I can bother them individually

**Comment by Olivia-Chiong** [comment]
@pawan92 The Tuesday 6:30 pm meeting is the general project meeting. Suggest you try to go to this.

**Comment by pawan92** [comment]
@Olivia-Chiong Planning on it. I got some feedback from @jpmikesell but it wasn't all the information we needed.

**Comment by jpmikesell** [comment]
Description: Food Oasis, foodoasis.la, is a website for food seekers in Los Angeles. Think of YELP for free food. We give people the tools to find food pantries or hot meals within a 2-mile radius of their current location. We have two teams of volunteers. One team works on the back and front end development, UX Research and Design. Another team, with the help of LA Works, validates the information of each organization. Our goal is to present valid data for our users. Future features will include creating accounts for users to receive nutritional education and tools for food rescue organizations to connect with each other.

Leadership: Jenny Mikesell, Product Owner, Github jpmikesell, John Darragh, Tech Lead, Github entrotech, Andrew Strauss, Product Manager, Github pageignited.

New logo attached

**Comment by entrotech** [comment]
The test site is at http://devla.foodoasis.net.
We also have a wiki with more details at https://github.com/hackforla/food-oasis/wiki

**Comment by entrotech** [comment]
And the Github url is http://github.com/hackforla/foodoasis

**Comment by pawan92** [comment]
Update: @ExperimentsInHonesty Got all the information. Not sure if this is supposed to be closed or open and reassigned to prioritized backlog. Please lmk.
