### ISSUE TITLE
Update Project Profile: LA TDM Calulcator

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/product-management#37]
### Dependency
~Waiting on implementation of https://github.com/hackforla/website/issues/989~
Waiting on implementation of https://github.com/hackforla/website/issues/1144

### Overview
Please review the following information for your project and provide any updates 

### Project card
https://www.hackforla.org/projects/tdm-calculator

### Action Items
Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
- [ ] title
- [ ] description
- [ ] image
- [x] leadership
   - [ ] Name 
   - [ ] Role 
   - [ ] Github Handle
   - [ ] Slack Member ID
- [x] links
  - [x] Github
  - [ ] Slack
  - [x] Test Site
  - [x] Demo Site
  - [x] Site
- [ ] looking
- [ ] technologies
- [ ] location
- [x] partner
- [ ] tools
- [x] status

**Comment by pawan92** [comment]
Reached out to Kevin via slack on Jan 12 letting him know about this ticket and to verify the information is correct and whether or not we need updates along with link to this ticket.

**Comment by pawan92** [comment]
**Progress:** Have reached out to and got a response from Kevin saying he will look into it on Jan 13th. Just pinged him today saying thanks and to let me know
**Blockers:** None
**Availability:** Good
**ETA:** This week

**Comment by KPHowley** [comment]
### **Updated Blurb:**

**The LA TDM Calculator**

The LA TDM Calculator is a web app, created in conjunction with the L.A. Department of Transportation, to help real estate developers design better projects for Los Angeles. The Calculator is being implemented alongside a new ordinance reducing over-parking and improving the infrastructure to incentivize public transportation and discourage single occupancy vehicle trips.  

**Links:** Github
**Partner:** LA Department of Transportation  - LADOT (https://ladot.lacity.org/)
**Location:** Downtown LA, Remote
**Languages:** JavaScript, TSQL, SCSS, HTML, Dockerfile
**Technologies:** ReactJS, Express, Node.js, Microsoft SQL Server, Docker, Azure App Service, SCSS , Figma
**Open Roles :** Front End Developers, Experienced Back End Developers, UI/UX Designers and Researchers

### **Leadership- Remove:**  

- Nicole Doan
- Mindy Morgan
- Fang Lui


### **Slack:**

 #tdm-calculator

**Comment by pawan92** [comment]
@KPHowley Bonnie says there are other individuals that need to be displayed under leadership. Bonnie says "PLEASE REVIEW THIS AGAIN"

**Comment by pawan92** [comment]
@KPHowley Any updates:
Progress:
Blockers:
Availability:
ETA:

**Comment by ExperimentsInHonesty** [comment]
New title for Kevin H
Product Manager / Stakeholder Project Rep.

New title for Bonnie 
Agile Coach / Primary Stakeholder Relationship Manager 

Add the following people
Vivek Jha 
Role: Product manager
GitHub: VJ1285
Slack: U019HFZ9WM6

Kevin Shih
Role: UX Research Lead
GitHub: kevinshih613
Slack: U01K4Q3EU6R

**Comment by akibrhast** [comment]
## Overview
Update implement in pull request #1008 

## Action Items
1.  [request](https://github.com/hackforla/product-management/issues/37#issuecomment-761925373) 
2.  [request](https://github.com/hackforla/product-management/issues/37#issuecomment-772230227)

- [x] Update Title
- [x] Update Blurb
- [x] Update Partner
- [x] Update Technologies
- [x] Update Leadership

**Comment by ExperimentsInHonesty** [comment]
@KPHowley @VJ1285 it seems like the updates have been made.  Can you review and mark this as closed if satisfactory.

**Comment by VJ1285** [comment]
@ExperimentsInHonesty 

- [ ] We need to remove "The" from the project title
- [ ] Need to update the one sheet. Made minor edits to it. The updated one sheet can be found below
https://docs.google.com/document/d/1ORNo1bTC-Sx0Rd64_-XfTXj_dN15Wu1Feiax2gGNJTw/edit

**Comment by ExperimentsInHonesty** [comment]
@VJ1285 I have created an [issue](https://github.com/hackforla/website/issues/1144) on the Hack for LA website team to remove the "The" from the name.  Sorry for the delay.

**Comment by ExperimentsInHonesty** [comment]
Added Dependency.  This issue is waiting for this [issue](https://github.com/hackforla/website/issues/1144) to be resolved, so that pm can do signoff
