### ISSUE TITLE
Identify all the PM and POs needed

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/product-management#4]
### Overview
Identify all project managers required

### Action Items
- [x] List all projects that need PMs
   - [x] Review the product management staffing requirements identified in this document
- [x] Abi to reach out to Navariti to get some time with Bonnie (Sunday 8 am or 4 pm PST, Thursday and Friday preference 6, 7 pm, 8pm EST) - 2 hours a week for a month then maybe 1 hour after then 
- [x] Minty meeting (Mondays at 4.30PST)-Bonnie has begun a chat with Minty 
- [ ] Not Today Project - Product School Ad? (Interview and review of documents) -On hold for now, will revisit as a part of the civic opportunity special projects initiative  -Abi to follow up on this.
- [ ] Home Unite Us- Temporary, Current PM is out sick.Could be more permanent if they have a background in marketing and communications(Beautiful slide deck, build stakeholder confidence) -Bonnie to follow up with available resources to identify possible fit.
- [ ] Civic Tech Index-Great writer, interviewer, a good fit would be someone that has been a UX Writer, Journalist or script writer.

### Resources/Instructions
https://docs.google.com/document/d/1_kuRjVg4X0YYnagV53DHjeiVKN4prs9ktI0WiqEHWSU/edit?usp=sharing

**Comment by abi-a** [comment]
The only outstanding ones are Not Today Project, Hello Gov and Lucky Parking. Others have been addressed

**Comment by abi-a** [comment]
Abi to write up a draft of the job description and add here for bonnie to review. Google Document, this should be sent to the project team for their review. Document should have repo links so the people can view it from there

**Comment by ExperimentsInHonesty** [comment]
This article will be useful for the messaging project pm https://www.theguardian.com/commentisfree/2020/sep/08/robot-wrote-this-article-gpt-3
