### ISSUE TITLE
Add all legacy PMs to the product-management team

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/product-management#41]
### Overview
We need to have all PM on the GitHub repo for product so that they can do updates on their issues

### Action Items
- [ ] PMs
   - [ ] Add all product manager github handles that you have update issues for to the comments below
- [ ] HfLA GitHub Owner
   - [ ] add those github handles to the pm team
  
### Resources/Instructions
Team: https://github.com/orgs/hackforla/teams/product-managment-write

**Comment by pawan92** [comment]
LA TDM Product Manager: Kevin Howley (@KPHowley)
New Schools Today Product Manager: Joshua Bubar (@jbubar)

**Comment by tarang100** [comment]
@ExperimentsInHonesty
   - [ ] Please add the following Github handles to the PM team
      - [ ] Civic Opportunity Project: Ray Frambro (@rfambro2)
      - [ ] Public Tree Map - Emily (@emillipede)
      - [ ] Record Clearance Project - Daniel Lee (@j100892)
      - [ ] Undebate - Missing

**Comment by ahdithebomb** [comment]
@ExperimentsInHonesty 

    - [ ] 311 Data: Pras (pras4u), already on github 
    - [ ] Civic Tech Index - Olivia, (Olivia-Chiong ), already on github 
    - [ ] Civc Tech Structure- Bonnie (ExperimentsInHonesty), already on github

**Comment by ggrrettcchhenn** [comment]
Please add the following PMs:
Record Clearance Project - Gretchen Howard (ggrrettcchhenn)
Record Clearance Project - Myranda Pierce (myrandi)

**Comment by ExperimentsInHonesty** [comment]
- [ ] Add Andrew from Food Oasis
