### ISSUE TITLE
Update Project Profile: Public Tree Map

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/product-management#46]
### Overview
As a product manager, I need to make sure that all the projects that are listed on the HfLA website are up to date so that my customers(visitors) can get an accurate picture of each of the projects.

### Project card
https://www.hackforla.org/projects/public-tree-map

### Action Items

- [ ] [INSERT TEAM NAME HERE] Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [ ] title
      - [ ] description
      - [ ] image
      - [ ] leadership
         - [ ] Member Name
         - [ ] Role
         - [ ] Slack Member ID
         - [ ] Github Handle
     - [ ] links
        - [ ] Github
        - [ ] Slack
        - [ ] Test Site
        - [ ] Demo Site
        - [ ] Site
     - [ ] looking
     - [ ] technologies
     - [ ] location
     - [ ] partner
     - [ ] tools
     - [ ] status

**Comment by tarang100** [comment]
Posted the issue in the Public Tree Map Slack channel on 11th January 2021 at 9:45 PM IST / 8:15 AM PST

Reached out to Emily on 14th January 2021 at 10:45 PM IST / 9:15 AM PST
```
Hi Emily, hope you are keeping well. I am PM with the HfLA Website and need your assistance in updating the information mentioned in the following issue. Request you to please have a look at the same. Thank you!
https://github.com/hackforla/product-management/issues/46
```

**Comment by pawan92** [comment]
@tarang100 Update please:
Progress:
Availability:
Blockers:
ETA:

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty has reached out to Emily.  Will provide an update here when I hear back.

**Comment by ExperimentsInHonesty** [comment]
Emily is unreachable (tried emailing and slacking).  Will be marking the Public Tree Map project as complete.
