### ISSUE TITLE
Create a One Sheet: GreenEarthOS (formally known as Climate)

### ISSUE THREAD

**Issue by vishrut-goel** [hackforla/product-management#64]
### Dependency
Waiting for a logo https://github.com/hackforla/GreenEarthOS/issues/56

### Overview
Create the project one sheet so it can be shared with stakeholders and funders.

### Action Items
- [x] Check to confirm project does not already have a one sheet
- [x] Speak to the team to get an overview of the project
- [x] Include project name 
- [ ] Include project logo
- [x] Create history/last 6 months
- [x] Create roadmap/next 6 months
- [x] Include last updated date

### Resources/Instructions
Check issue #3 for sample one sheets
[Climate Project One Sheet](https://docs.google.com/document/d/1mVxXVz2sTPyzJ9LjeJXq2rv2Pstc9vffh5wftIusAMo/edit
)
[Creation of Project Card](https://github.com/hackforla/climate-project/issues/3)

**Comment by sayalikotkar** [comment]
Progress: Draft complete - https://docs.google.com/document/d/1mVxXVz2sTPyzJ9LjeJXq2rv2Pstc9vffh5wftIusAMo/edit
Blockers: Waiting for the project name & contact email to be finalized
Availability: 2 hours
ETA: 15th Feb

**Comment by ExperimentsInHonesty** [comment]
This issue is completed https://github.com/hackforla/product-management/blob/master/project-one-sheets/GreenEarthOS-One-Sheet.pdf
