### ISSUE TITLE
Update project one sheet: hackforla.org

### ISSUE THREAD

**Issue by muhabdulkadir** [hackforla/product-management#67]
### Overview: 
We need to update the one sheet so that new team members can understand where the project is in its lifecycle

### Action Items

- [ ] Review the existing one sheet
- [ ] Meet with the team product managers to work on updates with them

### Resources/Instructions
[HackforLA.org One Sheet](https://docs.google.com/document/u/1/d/1hIAKyJwDHknPjn7I-RmZeCu_RkK-Zw4YNBA_-Ygqdoc/edit)

**Comment by pawan92** [comment]
Update:
Progress: Looked through all the "in development" pages and commented on them whether they're completed or I had any questions. Looking through the pages on figma for whats missing and adding them to the one sheet
Blockers: None
Availability: Yes
ETA: 2/2/2021

**Comment by Olivia-Chiong** [comment]
@pawan92
Progress:
Blocks:
Availability:
ETA:

**Comment by pawan92** [comment]
Talked to Bonnie and will have updates by sunday (2/7)

**Comment by pawan92** [comment]
Update: Updated one sheet with all the upcoming pages with a brief description on what and why we need it

**Comment by ExperimentsInHonesty** [comment]
@pawan92 Thank you for the detailed work.  Let's discuss at our next Hack for LA Product Mgr meeting.

**Comment by ExperimentsInHonesty** [comment]
@tarang100 please make an agenda/issue for the HfLA product manager meeting and put this on it.

**Comment by ExperimentsInHonesty** [comment]
skipped one more week, but no more.

**Comment by ExperimentsInHonesty** [comment]
I finished updating it from the awesome work that @pawan92  did.  I made a new page with the url: https://docs.google.com/document/d/15euICw3ueDNu4qZaS5rrjLRVn4QBYCjJT92AdJ28jJg/edit. But kept the old page so that we have the wording for sections that did not get included: https://docs.google.com/document/d/1hIAKyJwDHknPjn7I-RmZeCu_RkK-Zw4YNBA_-Ygqdoc/edit
