### ISSUE TITLE
Update Project One Sheet:  HomeUniteUS

### ISSUE THREAD

**Issue by valerianprince** [hackforla/product-management#68]
### Overview
Create or update the project one sheet so it is current and can be shared with stakeholders and funders.

### Action Items
- [x] Check to confirm project overview is accurate
- [x] Include project logo
- [x] Update history/last 6 months
- [x] Update roadmap/next 6 months
- [x] Update last updated date

### Resources/Instructions
Check issue #3 for sample one sheets
[One Sheet](https://docs.google.com/document/d/1G0S_BKeLtIg8vzhBzSzV3Z-4U9mDbLaRlIw1MZjsZms/edit)

**Comment by ExperimentsInHonesty** [comment]
Reach out to Alex Le @quyenvhle

**Comment by shaswa** [comment]
Reached out to Alex on Slack for Updates

**Comment by shaswa** [comment]
Alex will discuss with Abby about the updates and get back to me so that I can update the OneSheet

**Comment by ExperimentsInHonesty** [comment]
I spoke to Abby, and she said by end of next week (before next friday meeting).  in the meantime its missing its footer.  @shaswa please add that, by copying the footer template from one of the finished one sheets.  Here they are: https://github.com/hackforla/product-management/tree/master/project-one-sheets

**Comment by shaswa** [comment]
Will update the footer before the PM meeting tomorrow

**Comment by shaswa** [comment]
Added HackForLA link and GitHub to footer. Asked Alex for contact information

**Comment by Olivia-Chiong** [comment]
@shaswa did you manage to speak to Abby or Alex on this?

**Comment by quyenvhle** [comment]
Updated OneSheet, waiting @abbyhipp' review

**Comment by shaswa** [comment]
Meeting Alex tomorrow for a sync up

**Comment by shaswa** [comment]
Met Alex yesterday and reviewed OneSheet

**Comment by shaswa** [comment]
The only thing left is Contact email in the footer. Waiting for Abby to provide the email address.

**Comment by ExperimentsInHonesty** [comment]
@shaswa They have an email, I looked it up and added it.  I changed the formatting to be consistent with our other worksheets (changed text color to match logo, made the top paragraph a little larger text (since there was room for it).

I have some questions about the content on this.  So I am going to slack Abby about adding a discussion of this to our Home Unite Us mgmt meeting (its the second time listed on here: https://www.hackforla.org/projects/home-unite-us) .  If you are able to come, please do.  If the time does not work for you let me know in a comment below and put this back into the review column.  

Thanks!

**Comment by shaswa** [comment]
Thank you, @ExperimentsInHonesty! I will attend the meeting on Saturday, just added it to my calendar.

**Comment by shaswa** [comment]
@ExperimentsInHonesty I should have asked this earlier. Is the meeting time on the website in EST or PST?

**Comment by Olivia-Chiong** [comment]
Meeting time on the website is always in your own timezone.

**Comment by shaswa** [comment]
@Olivia-Chiong Thank you for the information! I wrongly assumed the time to be in PST and missed today's meeting. 

I think if the website can determine user's timezone, it should be displayed in the UI too to improve accuracy. I will bring it up in the Hack for LA website PM meeting.

**Comment by Olivia-Chiong** [comment]
@shaswa any updates?

Progress:
Blocks:
Availability:
ETA:

**Comment by shaswa** [comment]
@Olivia-Chiong I should have had moved this to in review column. 

Tagging @ExperimentsInHonesty as per comment above

**Comment by Olivia-Chiong** [comment]
SPY logo
![image](https://user-images.githubusercontent.com/75456721/113447055-f856de80-93ad-11eb-95cf-e9fe7be54632.png)

**Comment by ExperimentsInHonesty** [comment]
@Olivia-Chiong the one sheet is done

**Comment by Olivia-Chiong** [comment]
Done
