### ISSUE TITLE
Update One Sheet: VRMS

### ISSUE THREAD

**Issue by alexilee** [hackforla/product-management#69]
### Overview
Update the project one sheet so it is current and can be shared with stakeholders and funders.

### Action Items
- [x]  Check to confirm project overview is accurate
- [x]  Include project logo
- [x]  Update history/last 6 months
- [x]  Update roadmap/next 6 months
- [x]  Update last updated date

### Resources/Instructions
Check issue [#3](https://github.com/hackforla/product-management/issues/3) for sample one sheets
[VMRS One Sheet](https://docs.google.com/document/d/1lsRUAAMs1b60LOqQb9H6c4Ky9AbQ7QN4FB1XNErKxEs/edit)

**Comment by ExperimentsInHonesty** [comment]
After talking with Alex at the PM meeting, I reached out to Adam on VRMS via slack and told him about why Alex was there.  Waiting for update from Alex after next contact.

**Comment by alexilee** [comment]
I messaged both Adam Spar and Khushboo Shah on slack in order to set up time to get the information necessary to update the one sheet.

**Comment by alexilee** [comment]
No reply from either PM. Bumped the conversation in Slack to initiate a response.

**Comment by khushbooshah-PM** [comment]
Meeting with Alex today at 3 pm to discuss.

**Comment by alexilee** [comment]
Met with Khushboo today and we are working on updating the one sheet.

**Comment by ExperimentsInHonesty** [comment]
@alexilee please provide an update

1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by alexilee** [comment]
1. Worked with Khushboo to update the one sheet. Project description reviewed and last updated date added. Timelines still need to be updated and it needs to be reduced to one page.
2. Adam has been busy with other things. Khushboo has had some emergency situations the last week and will have more time tomorrow. Waiting on PMs on project to finish updating one sheet.
3. I'm not quite sure if you are asking for my general availability or specifically for this issue so I will provide both:
-General availability: I am available on most weekdays throughout the day and evening.
-Availability specific to issue: I am available all of today and will occasionally be online over the weekend.
4. This issue should be wrapped up by this weekend.

**Comment by alexilee** [comment]
One sheet has been updated. Ready for review.

**Comment by ExperimentsInHonesty** [comment]
@alexilee Thank you for the update.

**Comment by ExperimentsInHonesty** [comment]
@alexilee Please see my notes on the one sheet.  Feel free to contact me with any questions.

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty will attend their meeting and figure out what is needed.

**Comment by ExperimentsInHonesty** [comment]
wrote to Adam

**Comment by ExperimentsInHonesty** [comment]
asked for a meeting with Adam.

**Comment by ExperimentsInHonesty** [comment]
emailed Adam again.

**Comment by ExperimentsInHonesty** [comment]
Made some minor edits and olivia closed this.
