### ISSUE TITLE
Update One Sheet: BallotNav

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/product-management#71]
### Overview
Update the project one sheet so it is current and can be shared with stakeholders and funders.

### Action Items
- [x] Check to confirm project overview is accurate
- [x] Include project logo
- [x] Update history/last 6 months
- [x] Update roadmap/next 6 months
- [x] Update last updated date
- [ ] Get approval from org lead
- [ ] Make pdf 
   - [ ] name it: BallotNav-Project-One-Sheet.pdf 
   - [ ] put in repository
   - [ ] add link to the pdf (in repository in the comments below)

### Resources/Instructions
[Updated BallotNav one-sheet](https://docs.google.com/document/d/1m6Dvw9D6eJhBCV5lLLlr0j27455F1BrAEclsWDePgnw/edit)

**Comment by Arjayellis** [comment]
@aadi-singh01 @ExperimentsInHonesty One-sheet has been updated. We will be getting the roadmap completed this weekend. Please let me know if we need to make any edits.

**Comment by Arjayellis** [comment]
@Olivia-Chiong Looping you in as I believe you are heading this.

**Comment by Olivia-Chiong** [comment]
Thanks @Arjayellis please see notes in documents and let me know if you are agreeable to the changes.

**Comment by Arjayellis** [comment]
@Olivia-Chiong looks good!

**Comment by ExperimentsInHonesty** [comment]
@Arjayellis Please make a pdf of this called: BallotNav-Project-One-Sheet.pdf , put it in the repository, and add the url here.

**Comment by Arjayellis** [comment]
https://github.com/hackforla/product-management/blob/master/BallotNav-Project-One-Sheet.pdf
