### ISSUE TITLE
Update One Sheet: LA TDM

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/product-management#75]
### Overview
Create or update the project one sheet so it is current and can be shared with stakeholders and funders.

### Action Items
- [x] Check to confirm project overview is accurate
- [x] Include project logo
- [x] Update history/last 6 months
- [x] Update roadmap/next 6 months
- [x] Update last updated date

### Resources/Instructions
Check issue #3 for sample one sheets
[One Sheet for LA TDM](https://docs.google.com/document/d/1ORNo1bTC-Sx0Rd64_-XfTXj_dN15Wu1Feiax2gGNJTw/edit)

**Comment by Olivia-Chiong** [comment]
@rohit-309 
Progress:
Blocks:
Availability:
ETA:

**Comment by tarang100** [comment]
Bonnie has reached out to Kevin and Vivek in the LA TDM Slack Channel

**Comment by KPHowley** [comment]
@VJ1285 @ExperimentsInHonest - I just did a quick pass on updating the timelines and bullet points on this.

**Comment by ExperimentsInHonesty** [comment]
@KPHowley 
I deleted this: "Due to legal regulations around pending legislation user testing was previously unavailable "
I changed some of the references to lacp and ladot

This doesn't sound right, am I misunderstanding something... we have been on their server for staging and production for a while.
MVP scheduled for - Summer 2021 
Production and Staging migration to LADOT servers on their Azure platform.

**Comment by Olivia-Chiong** [comment]
@KPHowley 

Progress:
Blocks:
Availability:
ETA:

**Comment by VJ1285** [comment]
@Olivia-Chiong The one sheet is updated. @KPHowley take a look it and if everything looks good please close the issue.

**Comment by Olivia-Chiong** [comment]
Moved to review column for @ExperimentsInHonesty to review.

**Comment by ExperimentsInHonesty** [comment]
@VJ1285 @KPHowley this needs to be the very first agenda item at our saturday meeting for the following reasons
1. its not one page (its literally called a one sheet why is it two pages )
2. didn't answer my question above about schedule

**Comment by VJ1285** [comment]
1. Edited it to fit in one page
2. We can discuss the "schedule" item tomorrow.

**Comment by ExperimentsInHonesty** [comment]
@KPHowley @VJ1285 - Perfect!  Please open a new issue on your repository that has the following and then close this issue by adding the link to the issue in a comment below.

```
Title:  Update the One Sheet Q2 2021

Body:
### Dependency
Date is: March 27th, 2021

### Overview
We need to keep the project one sheet up to date, so that we can communicate with Partners, Volunteers and Potential Funders

### Action Items
- [ ] Review the existing one sheet and make relevant changes
- [ ] Open issue on the https://github.com/hackforla/product-management/ repo for review

### Resources
[Editable version](https://docs.google.com/document/d/1ORNo1bTC-Sx0Rd64_-XfTXj_dN15Wu1Feiax2gGNJTw/edit)
[PDF version](https://github.com/hackforla/product-management/blob/master/project-one-sheets/TDM-Calculator-Product-One-Sheet.pdf)
```

**Comment by ExperimentsInHonesty** [comment]
I have added a task item to an existing issue that is open on the hackforla website repo.  The task item will add the pdf to the TDM calc project board as a link called Overview.

https://github.com/hackforla/website/issues/1056

**Comment by VJ1285** [comment]
@ExperimentsInHonesty - Please re-review the pdf of the one-sheet. I removed the periods from the bullet points from the items under "Alpha Version"

**Comment by ExperimentsInHonesty** [comment]
@VJ1285 I am not sure what you are asking for on this part 
https://github.com/hackforla/website/issues/1119#issue-816542083
" description - Need to update the one-page"
If we need to make a change to the pdf then we just upload a new pdf after I sign off and it automatically updates on the website.   Can you confirm that is what you are asking for, is a change to the existing pdf that is showing up here: https://github.com/hackforla/product-management/blob/master/project-one-sheets/TDM-Calculator-Product-One-Sheet.pdf

**Comment by ExperimentsInHonesty** [comment]
@VJ1285 I just looked at https://docs.google.com/document/d/1ORNo1bTC-Sx0Rd64_-XfTXj_dN15Wu1Feiax2gGNJTw/edit. which is what is linked above as the current one sheet, but it has the same date as the pdf now online here: https://github.com/hackforla/product-management/blob/master/project-one-sheets/TDM-Calculator-Product-One-Sheet.pdf

so what is the difference?

**Comment by VJ1285** [comment]
@ExperimentsInHonesty - Seems like the new pdf is uploaded on the pdf page. I updated the pdf on 2/25 where I removed all the periods. Seems like everything is up to date now.
